# C'est un titre - leçon python second journée

### le text plus petit

##### le texte plus petite 

Voila quelque notes. Laissez des notes pour référence future. 

#### Créer une sous-titre . 

Assetez Ctrl + Enter à exécuter le Markdown.   

Voici un sous-titre pour l'importation des paquets.

##### Import tous les paquets 

In [1]:
import pandas as pd 
import numpy as np


In [10]:
df = pd.DataFrame()

### Practique des Variables

Créez quatre variables: une pour chaque type d'objet python. Nommez les variables comme vous préférez. An example of a change. 

In [11]:
nombre = 8.5

In [ ]:
# Example 1 - Float
nombre = 8.5


In [29]:
# Float
nombre = 8.5

# Integer
Age = 5

# Andrew 
Country_name = "Cote d'Ivore 45948632"

# Booleans 
CIV = True

In [32]:
type(CIV)

bool

In [34]:
# Float
nombre = 8.5

# nombre fois quatre
nombre * 4

34.0

In [35]:
# Integer
Age = 5 

# Age fois quatre
Age * 2

10

In [37]:
Nom = 'Andrew' 

# Nom plus Nom
Nom+Nom

'AndrewAndrew'

In [45]:
Country = ' CIV'


# Nom fois deux
Nom + Country

'Andrew CIV'

In [41]:
# Nom - Nom

Nom - Nom

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [46]:
# Nom / Nom 

Nom / Nom

TypeError: unsupported operand type(s) for /: 'str' and 'str'

### Booleans 

In [47]:
CIV = True 

In [48]:
print(CIV)

True


In [49]:
CIV * 3

3

In [51]:
VRS = False 

In [52]:
print(VRS)

False


In [53]:
VRS * 3

0

## Practique des listes

Placez les quatre variables dans une liste. Nommez la liste - au_hasard. Print() ensuite.

In [54]:
the = 'the-the-the'
four = 4
chat = True 
mini = 4.5

au_hasard = [the, four, chat, mini]

print(au_hasard)

['the', 4, True, 4.5]


### Isolez la première observation de la liste.  

In [55]:
au_hasard[0]

'the'

### Isolez la seconde observation de la liste. 

In [56]:
au_hasard[1]

4

### Isolez les deuxième et troisième objets.

In [58]:

print('[0]')
au_hasard[1:3]

['the', 4, True, 4.5]


[4, True]

In [68]:
print(au_hasard[0:3])

['the', 4, True]


#### Country List 

In [69]:
country_list = ["Cote d'Ivoire", 'Algerie', 'Senegal', 'Benin']

In [70]:
country_list[0]

"Cote d'Ivoire"

In [71]:
country_list[0]

["Cote d'Ivoire", 'Algerie', 'Senegal']

### Créez deux listes d'entiers et de floats: une avec trois valeurs et une autre avec quatre valeurs. 

Nommez les listes: hauteur et poids.

In [3]:

#          [0]   [1]   [2]
hauteur = [1.6, 1.74, 1.59]
poids =   [65,    80,   54, 62]
print(hauteur)
print(poids)

[1.6, 1.74, 1.59]
[65, 80, 54, 62]



### Ajouter les listes ensemble.

In [73]:
hauteur + poids

[1.6, 1.74, 1.59, 65, 80, 54, 62]

### Essayez de multiplier les listes

In [74]:
hauteur*poids

TypeError: can't multiply sequence by non-int of type 'list'

## Numpy Arrays

Transformez les listes en arrays de numpy pour les calculs. 

In [4]:
HAUTEUR = np.array(hauteur)
POIDS = np.array(poids)

In [80]:
HAUTEUR  = np.array(hauteur)
print(HAUTEUR)
print(type(HAUTEUR))

[ 1.6   1.74  1.59]
<class 'numpy.ndarray'>


In [81]:
POIDS  = np.array(poids) 
print(POIDS)

[65 80 54 62]


### Additionez les numpy arrays. Est-ce que vous pensez que ça va marcher?

In [82]:
HAUTEUR + POIDS

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

### Additionez une observation à HAUTEUR

In [5]:
HAUTEUR = np.append(HAUTEUR, np.nan) 
print(HAUTEUR)

[ 1.6   1.74  1.59   nan]


### Additionez les Numpy Arrays

In [90]:
HAUTEUR + POIDS

array([ 66.6 ,  81.74,  55.59,    nan])

### Produire la Variable de IMC en utilisant les Numpy Arrays. 

In [91]:
IMC = POIDS/(HAUTEUR **2)
print(IMC)

[ 25.390625    26.42356982  21.35991456          nan]


# Pause 

Environ 15 min. 

# Dictionaries and Pandas DataFrames


### Produire le dictionnaire de hauteur et poids

    dictionnaire = {'key' : list or np.array, 
                   'nom' : [valeur, valeur, valeur...]}

In [12]:
IMC_data = {'heights': HAUTEUR, 
           'weight': POIDS}

In [13]:
print(IMC_data)

{'heights': array([ 1.6 ,  1.74,  1.59,   nan]), 'weight': array([65, 80, 54, 62])}


### Isoler les données de la variable hauteur

In [14]:
IMC_data['heights']

array([ 1.6 ,  1.74,  1.59,   nan])

### Isoler la seconde observation dans le 'array' de la variable hauteur

In [16]:
IMC_data['heights'][1]

1.74

### Ajoutez une liste de noms au dictionnaire

In [17]:
nom = ['Fatima', 'Ahmadou', 'Michael', 'Frank']

In [18]:
IMC_data['nom'] = nom

In [19]:
print(IMC_data)

{'heights': array([ 1.6 ,  1.74,  1.59,   nan]), 'weight': array([65, 80, 54, 62]), 'nom': ['Fatima', 'Ahmadou', 'Michael', 'Frank']}


### Transformez le dictionnaire en un DataFrame Pandas

Nommez le dataframe: df

In [20]:
df = pd.DataFrame(IMC_data)

In [21]:
df

heights      nom  weight
0     1.60   Fatima      65
1     1.74  Ahmadou      80
2     1.59  Michael      54
3      NaN    Frank      62

In [22]:
df.set_index('nom')

heights  weight
nom                     
Fatima      1.60      65
Ahmadou     1.74      80
Michael     1.59      54
Frank        NaN      62

### Ajoutez une liste pour la variable Note au DataFrame

In [ ]:
notes = ['A', 'C', 'B', 'C']

In [ ]:
df['notes'] = notes

In [ ]:
df

### Exporter des données dans un fichier Excel, Stata ou csv

In [ ]:
# définir le fiche
fiche = '/media/lightner/TOSHIBA EXT/Python Tutorial/'

In [ ]:
df.to_csv(fiche+ 'file.csv')
df.to_stata(fiche+ 'file.dta')
df.to_excel(fiche+ 'file.xls')

### Importer des données de CIV dans le 'Data' fiche

Créer le variable - fiche

In [ ]:
fiche = ''

In [ ]:
fiche = '/media/lightner/TOSHIBA EXT/Python Tutorial/PracticeData/'

### Lire les fichiers CSV

#### Utilitez pd.read_csv()

dataframe = pd.read_csv()

In [ ]:
CIV_employ = pd.read_csv(fiche+'CIV_employ.csv') 

In [ ]:
CIV_employ.head()

In [ ]:
CIV_export = pd.read_csv(fiche+'CIV_export.csv') 

In [ ]:
CIV_export.head()

#### Ajouter les données de export à CIV_employ

In [ ]:
CIV_employ['exports_merch_dol']  = CIV_export['exports_merch_dol']

In [ ]:
CIV_employ.head()

### Importer des données de CIV dans le 'Data' fiche

In [ ]:
China_donnee = pd.read_csv(fiche+'China.csv')

In [ ]:
China_donnee.head()

#### Append les DataFrames ensemble

In [ ]:
data = CIV_employ.append(China_donnee)

In [ ]:
data['countryname'].unique()

#### Générer des variables de changement

D'abord, nous réinitialisons l'index. 

In [ ]:
data = data.sort_values(['countryname','year']).set_index(['countryname','year'])

In [ ]:
data.head()

Ensuite, nous utilitons le fonction: DataFrame.pct_change(# number of time dimensions)

In [ ]:
data['export_pct_change'] = data['exports_merch_dol'].pct_change(1)

In [ ]:
data.head()

### Créer une variable de croissance avec l'emploi dans l'agriculture

In [ ]:
data['employ_pct_change'] = data['employ_share_ag'].pct_change(1)

### Réinitialiser l'index original

In [ ]:
data.reset_index(inplace=True)

In [ ]:
data.tail()

### Supprimer variable 'Unnamed: 0' 

In [ ]:
data.columns

In [ ]:
data = data.drop('Unnamed: 0', axis=1)

In [ ]:
data.head()

### Drop countrycode

In [ ]:
data = data.drop('countrycode', axis=1)

In [ ]:
data.head()

### Sélectionner des observations avec une croissance positive des part de l'emploi dans l'agriculture

In [ ]:
data[data['employ_pct_change']>0]

## Comment cela marche-t-il?

In [ ]:
data['la déclaration est vraie'] = data['employ_pct_change']>0

In [ ]:
data.head()

### When Quand je place 'data []' autour de la déclaration, les pandas ne prennent que les observations qui sont 'True'

In [ ]:
data[data['employ_pct_change']>0]

### Sélectionner des observations avec une croissance positive des exportations 

In [ ]:
data[data['export_pct_change']>0].head()

### Générer une variable binaire de croissance positive des exportations

In [ ]:
data['ex croissance positive'] = np.where(data['export_pct_change']>0, 1, 0)

In [ ]:
data.head()

### ### Générer une variable binaire de croissance positive des part de l'emploi dans l'agriculture

In [ ]:
data['ag croissance positive'] = np.where(data['employ_pct_change']>0, 1, 0)

In [ ]:
data.head()

#### Générer des statistiques récapitulatives de base

In [ ]:
data.describe()

### Pause 

# Visualisations 

In [ ]:
# Choisissez bokeh comme extension
hv.extension('bokeh')

#### Options de base

La première section crée la fenêtre de sortie et modifie la mise en forme des visuels.

In [ ]:
# Choisissez la taille de sortie pour les graphiques
%output size=200

In [ ]:
data.columns

### Scatter Plot

In [ ]:
%%opts Scatter [width=250, height=250, tools=['hover']] (size=5)
                 
scatter1 = hv.Scatter(data, 
                      # X - Variable 
                      kdims= ['employ_share_ag'],
                      # y - variable (1) apres les variables ce que vous pouvez l'information
                      vdims = ['exports_merch_dol', 'year', 'countryname'])
scatter1

### Here is some ramdom data to plot

In [ ]:
import numpy as np

xx = np.array([-0.51, 51.2])
yy = np.array([0.33, 51.6])
means = [xx.mean(), yy.mean()]  
stds = [xx.std() / 3, yy.std() / 3]
corr = 0.8         # correlation
covs = [[stds[0]**2          , stds[0]*stds[1]*corr], 
        [stds[0]*stds[1]*corr,           stds[1]**2]] 

m = np.random.multivariate_normal(means, covs, 1000).T
au_hasard = pd.DataFrame()
au_hasard['1'] = m[0]
au_hasard['2'] = m[1]

In [ ]:
%%opts Scatter [width=250, height=250, tools=['hover']] (size=3)
    
scatter1 = hv.Scatter(au_hasard, 
                      # X - Variable
                      kdims= ['1'],
                      # Y - Variable
                      vdims = ['2'])
scatter1

### Histogram 

In [ ]:
%%opts Histogram [width=250, height=250, tools=['hover']]
   

df_hist = data['export_pct_change']
df_hist = df_hist.dropna().as_matrix()
frequencies, edges = np.histogram(df_hist, 20)
hv.Histogram(frequencies, edges)

### créer un histogramme de changement dans la part de l'emploi

In [ ]:
%%opts Histogram [width=250, height=250, tools=['hover']]
   

df_hist = data['employ_pct_change']
df_hist = df_hist.dropna().as_matrix()
frequencies, edges = np.histogram(df_hist, 20)
hv.Histogram(frequencies, edges)

In [ ]:
%%opts Curve {+framewise}
data_curve = data.sort_values(['countryname','year']).set_index(['countryname','year'], drop=False)
points = [(data_curve['year']["Côte d'Ivoire"][i], data_curve['exports_merch_dol']["Côte d'Ivoire"][i]) for i in range(1991,2013)]

hv.Curve(points)

## Générer la même intrigue en utilisant la Chine

In [ ]:
%%opts Curve {+framewise}
data_curve = data.sort_values(['countryname','year']).set_index(['countryname','year'], drop=False)
points = [(data_curve['year']["China"][i], data_curve['exports_merch_dol']["China"][i]) for i in range(1991,2013)]

hv.Curve(points)

### Pause 

# Regression 

### Télécharger télécharger les données ODI comme 'df'

#### Ajouter ', sep = '|' entre les parenthèses

In [ ]:
df = data = pd.read_csv(fiche + 'ODI-Portal_Feb2017.csv', sep='|')

#### Ajouter un terme constant à l'ensemble de données

In [ ]:
df['Constant'] = 1

In [ ]:
print(list(df))

#### Liste des variables indépendantes dans les régressions

In [ ]:
# Create lists of variables to be used in the first regression
Xvars_1 = ['export_conc_index', 'Constant']
# Create lists of variables to be used in the second regression
Xvars_2 = ['export_conc_index' , 'GVA_share_ag', 'Constant']
# Create lists of variables to be used in the third regression
Xvars_3 = ['export_conc_index' , 'GVA_share_ag','LP_manu', 'Constant']

In [ ]:
# Estimate an OLS regression for each set of variables
# First Regression
# order = (dependent variable, independent variables, missing='drop')
reg1 = sm.OLS(df['GDPpc_2010'], df[Xvars_1], missing='drop').fit()
print('Results from Regression 1')
print(reg1.summary())

In [ ]:

# Second Regression 
reg2 = sm.OLS(df['GDPpc_2010'], df[Xvars_2], missing='drop').fit()
print()
print('Results from Regression 2')
print(reg2.summary())

In [ ]:
# Third Regression
reg3 = sm.OLS(df['GDPpc_2010'], df[Xvars_3], missing='drop').fit()
print()
print('Results from Regression 3')
print(reg3.summary())

### Exporter les résultats dans un format attrayant

In [ ]:
from statsmodels.iolib.summary2 import summary_col

info_dict={'R-squared' : lambda x: "{:.2f}".format(x.rsquared),
           'No. observations' : lambda x: "{0:d}".format(int(x.nobs))}

results_table = summary_col(results=[reg1,reg2,reg3],
                            float_format='%0.2f',
                            stars = True,
                            model_names=['Export Conc',
                                         'Add GVA Share',
                                         'Add LP Manu'],
                            info_dict=info_dict,
                            regressor_order=Xvars_3)

results_table.add_title('Example - OLS Regression in Python')

print(results_table)

### Générer un code Latex pour une présentation attrayante

In [ ]:
a = results_table.as_latex()
print(a)

Malheureusement, j'ai dû apporter quelques modifications au Code Latex présenté ci-dessous. Cependant, les changements étaient petits.

- Effacer le \\
- Effacer le début {center} et la fin {center}
- Débarrassez-vous du premier début / fin {tabulaire} et placez les en-têtes dans la deuxième tabulaire {}

Si l'utilisateur ne souhaite publier que la table, placez le texte entre le code suivant:

    \documentclass[paper=a4, fontsize=11pt]{scrartcl} % A4 paper and 11pt font size

    \begin{document}
    
    ...
    
    \end{document}